### ISSUE TITLE
BUG: 'panic: runtime error: index out of range [-1]' using 'devcontainer snippet add'

### ISSUE THREAD

**Issue by stuartleeks** [stuartleeks/devcontainer-cli#56]
## Repro steps

With the templates/snpipets configured as per the docs examples:

```
devcontainer template add debian
devcontainer snippet add golang
```

## Expected behaviour

Snippet is added successfully

## Actual behaviour

The `devcontainer snippet add` comment encounters the following error:

```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/bradford-hamilton/dora/pkg/merge.mergeValues(0xc00000cfc0, 0x1, 0x1, 0xa29900, 0xc00007cc60, 0xf6df90, 0x0, 0x0, 0xc00000d680, 0x1, ...)
        /go/pkg/mod/github.com/stuartleeks/dora@v0.1.2/pkg/merge/merge.go:63 +0x1501
github.com/bradford-hamilton/dora/pkg/merge.mergeValues(0xf6df90, 0x0, 0x0, 0xa21a00, 0xc00007e8c0, 0xc00000d040, 0x1, 0x1, 0xf6df90, 0x0, ...)
        /go/pkg/mod/github.com/stuartleeks/dora@v0.1.2/pkg/merge/merge.go:46 +0x1168
github.com/bradford-hamilton/dora/pkg/merge.MergeJSON(0xc00001e980, 0x0, 0xc00001eb40, 0x0, 0x0, 0x0, 0xc00013ec00)
        /go/pkg/mod/github.com/stuartleeks/dora@v0.1.2/pkg/merge/merge.go:13 +0x1af
github.com/stuartleeks/devcontainer-cli/internal/pkg/devcontainers.mergeJSON(0xc000026044, 0x1b, 0xc0001a60c0, 0xc000026980, 0x11, 0xc0000269a0, 0x1f, 0x20, 0x40)
        /home/runner/work/devcontainer-cli/devcontainer-cli/internal/pkg/devcontainers/snippet.go:351 +0x1fc
github.com/stuartleeks/devcontainer-cli/internal/pkg/devcontainers.addFolderSnippetToDevContainer(0xc000026044, 0x1b, 0xc0001a60c0, 0xc00002a6ae, 0x6)
        /home/runner/work/devcontainer-cli/devcontainer-cli/internal/pkg/devcontainers/snippet.go:214 +0x331
github.com/stuartleeks/devcontainer-cli/internal/pkg/devcontainers.addSnippetToDevcontainer(0xc000026044, 0x1b, 0xc0001a60c0, 0x0, 0x0)
        /home/runner/work/devcontainer-cli/devcontainer-cli/internal/pkg/devcontainers/snippet.go:171 +0x100
github.com/stuartleeks/devcontainer-cli/internal/pkg/devcontainers.AddSnippetToDevcontainer(0xc000026044, 0x1b, 0x7ffcc3714577, 0x6, 0xa70642, 0x4)
        /home/runner/work/devcontainer-cli/devcontainer-cli/internal/pkg/devcontainers/snippet.go:164 +0x73
main.createSnippetAddCommand.func1(0xc000191080, 0xc000071940, 0x1, 0x1, 0x0, 0x0)
        /home/runner/work/devcontainer-cli/devcontainer-cli/cmd/devcontainer/snippet.go:80 +0xe4
github.com/spf13/cobra.(*Command).execute(0xc000191080, 0xc000071900, 0x1, 0x1, 0xc000191080, 0xc000071900)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc00012eb00, 0xc00017bf70, 0x1, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/runner/work/devcontainer-cli/devcontainer-cli/cmd/devcontainer/main.go:39 +0x2c7
```

(Thanks to @chrmarti for the heads-up on this)

**Comment by chrmarti** [comment]
Has that made it to Homebrew?

I just updated to 0.1.913729827 and see:
```
$ devcontainer snippet add golang                                                                                                                                                                                                   12.18.3
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/bradford-hamilton/dora/pkg/merge.mergeValues(0xc00000cfe0, 0x1, 0x1, 0x1625200, 0xc00007a870, 0x1b77cc0, 0x0, 0x0, 0xc00000d0e0, 0x1, ...)
	/go/pkg/mod/github.com/stuartleeks/dora@v0.1.4/pkg/merge/merge.go:33 +0x1568
github.com/bradford-hamilton/dora/pkg/merge.mergeValues(0x1b77cc0, 0x0, 0x0, 0x1625200, 0xc00007a8c0, 0xc00000d0a0, 0x1, 0x1, 0x1b77cc0, 0x0, ...)
	/go/pkg/mod/github.com/stuartleeks/dora@v0.1.4/pkg/merge/merge.go:46 +0x11ad
github.com/bradford-hamilton/dora/pkg/merge.MergeJSON(0xc00001e980, 0x0, 0xc00001eb00, 0x0, 0x0, 0x0, 0xc000143000)
	/go/pkg/mod/github.com/stuartleeks/dora@v0.1.4/pkg/merge/merge.go:13 +0x1af
github.com/stuartleeks/devcontainer-cli/internal/pkg/devcontainers.mergeJSON(0xc00002a004, 0x2b, 0xc0001ac090, 0xc000026a80, 0x11, 0xc000026aa0, 0x1f, 0x20, 0x40)
	/home/runner/work/devcontainer-cli/devcontainer-cli/internal/pkg/devcontainers/snippet.go:351 +0x1fc
github.com/stuartleeks/devcontainer-cli/internal/pkg/devcontainers.addFolderSnippetToDevContainer(0xc00002a004, 0x2b, 0xc0001ac090, 0xc0000245e1, 0x6)
	/home/runner/work/devcontainer-cli/devcontainer-cli/internal/pkg/devcontainers/snippet.go:214 +0x331
github.com/stuartleeks/devcontainer-cli/internal/pkg/devcontainers.addSnippetToDevcontainer(0xc00002a004, 0x2b, 0xc0001ac090, 0x0, 0x0)
	/home/runner/work/devcontainer-cli/devcontainer-cli/internal/pkg/devcontainers/snippet.go:171 +0x100
github.com/stuartleeks/devcontainer-cli/internal/pkg/devcontainers.AddSnippetToDevcontainer(0xc00002a004, 0x2b, 0x7ffeefbff681, 0x6, 0x167472f, 0x4)
	/home/runner/work/devcontainer-cli/devcontainer-cli/internal/pkg/devcontainers/snippet.go:164 +0x73
main.createSnippetAddCommand.func1(0xc000197600, 0xc00006da10, 0x1, 0x1, 0x0, 0x0)
	/home/runner/work/devcontainer-cli/devcontainer-cli/cmd/devcontainer/snippet.go:80 +0xe4
github.com/spf13/cobra.(*Command).execute(0xc000197600, 0xc00006d9d0, 0x1, 0x1, 0xc000197600, 0xc00006d9d0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000021080, 0xc000187f70, 0x1, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/devcontainer-cli/devcontainer-cli/cmd/devcontainer/main.go:39 +0x2c7
```

**Comment by stuartleeks** [comment]
Hmm, that's odd - I believe it should have been. 

I just created a new folder and ran the following commands successfully:

```bash
$ devcontainer template add debian
$ devcontainer snippet add golang
$ devcontainer version
0.1.913729827
```

Does `devcontainer version` show `0.1.913729827` for you?

**Comment by chrmarti** [comment]
Yes, also retried with a downloaded binary to rule out Homebrew and it still fails.

**Comment by stuartleeks** [comment]
Ok, thanks. I'll dig into it a bit more. Are your templates configured to use this repo? https://github.com/microsoft/vscode-dev-containers

**Comment by stuartleeks** [comment]
UPDATE: I had an old version of the templates. I can repro now on the latest templates...

**Comment by stuartleeks** [comment]
@chrmarti - I've just tested this on my machine with the [latest release](https://github.com/stuartleeks/devcontainer-cli/releases/tag/v0.1.917641514).

**Comment by chrmarti** [comment]
Works for me now with the latest release. Thanks!

**Comment by stuartleeks** [comment]
Hooray! Thanks for checking and letting me know 😀
